export const Subjects = [
  "Architecture",
  "Art Instruction",
  "Art History",
  "Dance",
  "Design",
  "Fashion",
  "Film",
  "Graphic Design",
  "Music",
  "Music Theory",
  "Painting",
  "Photography",
  "Animals",
  "Bears",
  "Cats",
  "Kittens",
  "Dogs",
  "Puppies",
  "Fiction",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Humor",
  "Literature",
  "Magic",
  "Mystery and detective stories",
  "Plays",
  "Poetry",
  "Romance",
  "Science Fiction",
  "Short Stories",
  "Thriller",
  "Young Adult",
  "Science & Mathematics",
  "Biology",
  "Chemistry",
  "Mathematics",
  "Physics",
  "Programming",
];
